version: '2.0.{build}'
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet build --no-restore  --verbosity m --configuration Release
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  - cmd: dotnet test --configuration Release > TestResult.txt
on_finish :
  # any cleanup in here
artifacts:
 - path: 'TestResult.txt'
 - path: '**\*.nupkg'
   name: NugetPackage
deploy: off