using Newtonsoft.Json;
using System;

// class generated by https://quicktype.io/

namespace MovieProject.Logic.Proxy.DTO
{
    public class ExternalMedia
    {
        [JsonProperty("Title")]
        public string Title;

        [JsonProperty("Year")]
        public string Year;

        [JsonProperty("Rated")]
        public string Rated;

        [JsonProperty("Released")]
        public string Released;

        [JsonProperty("Runtime")]
        public string Runtime;

        [JsonProperty("Genre")]
        public string Genre;

        [JsonProperty("Director")]
        public string Director;

        [JsonProperty("Writer")]
        public string Writer;

        [JsonProperty("Actors")]
        public string Actors;

        [JsonProperty("Plot")]
        public string Plot;

        [JsonProperty("Language")]
        public string Language;

        [JsonProperty("Country")]
        public string Country;

        [JsonProperty("Awards")]
        public string Awards;

        [JsonProperty("Poster")]
        public Uri Poster;

        [JsonProperty("Metascore")]
        public string Metascore;

        [JsonProperty("imdbRating")]
        public string ImdbRating;

        [JsonProperty("imdbVotes")]
        public string ImdbVotes;

        [JsonProperty("imdbID")]
        public string ImdbId;

        [JsonProperty("Type")]
        public string Type;

        [JsonProperty("Response")]
        public string Response;

        [JsonProperty("Error")]
        public string Error;
    }
}
